+++
date = "2019-01-25T00:00:00"
draft = false
tags = ["Spatial statistics", "geography", "college football", "recruiting"]
title = "The Geography of Oklahoma State Football Recruiting Under Mike Gundy"
summary = "A programmatic approach to the spatial dimensions of recruiting over time"
math = false
comments = true
+++

Anyone who reads PFB articles on recruiting or listens to Gundy's press
conferences around signing day knows that Oklahoma State's recruiting practices
are heavily scrutinized.

Whereas Gundy was energetic and highly motivated during his 

...not to mention creating some cool visuals, etc.

Rivals

Yet, apart from these two, the mean and median centers have changed
remarkably little over the past 14 years.



I'm eager to investigate spatial changes in the recruiting patterns of Oklahoma
State football over the last few years. Is the geographic scale more constricted
now than it once was? Has the mean center shifted toward Stillwater in the past
few years? If so, are these the effects of poorer recruiting efforts? I
currently have students working on similar projects for the University of
Nebraska and the University of Missouri to measure the geographic effect of
leaving the Big XII (i.e., did the mean center of recruits' hometowns shift
north for Nebraska and south or east for Missouri to reflect their conference
realignment and by how much?).

The process is mostly automated in that I use a web scraper to extract recruits'
hometowns and a geocoding API to find lat/lon locations of these hometowns.
Unfortunately, OSU's rosters only go back to 2015 (at least on okstate.com),
unlike Nebraska which has every roster from
[**1890**](http://www.huskers.com/SportSelect.dbml?DB_OEM_ID=100&SPID=22&SPSID=4&KEY=&Q_SEASON=1890)
(incredible!) to the present. Beyond this limitation, there are several problems
with my current methods: the geocoder doesn't appropriately find every hometown;
it places some cities in other countries (Charleston, AR in Argentina, for
example). Also, these are all the players on the _roster_, not simply recruits
who joined their freshman year. Obviously players that are on the team for more
than one year appear in this dataset multiple times. Both of these issues are
fixable. It will just take some time to sort through it. Accounting for JUCO
transfers and considering them as a part of the recruiting class of their first
year is difficult, but doable.

Also, the map could be improved. It would be best to not use red, of course, and
it would be cool to be able to click on a point and observe the corresponding
player and hometown. Per one of PFB's recent podcasts, it would also be
interesting to filter skill versus non-skill positions, but this would be much
more involved.

## All recruits (2006 - 2019)

```{r code = readLines("~/git-repos/okstate-fb-recruiting/map-all-recruits.R"), echo = FALSE, message = FALSE}
```
